export const common_phrases = [
	{
		eng: "God",
		hindi: "परमेश्वर",
	},
	{
		eng: "Word of God",
		hindi: "परमेश्वर का वचन",
	},
];
export const keyboard_keys = {
	consonants: {
		क: "ka",
		ख: "kha",
		ग: "ga",
		घ: "gha",
		ङ: "nga",
		च: "ca",
		छ: "cha",
		ज: "ja",
		झ: "jha",
		ञ: "ña",
		ट: "Ṭa",
		ठ: "Ṭha",
		ड: "Ḍa",
		ढ: "Ḍha",
		ण: "Ṇa",
		त: "ta",
		थ: "tha",
		द: "da",
		ध: "dha",
		न: "na",
		प: "pa",
		फ: "pha",
		ब: "ba",
		भ: "bha",
		म: "ma",
		य: "ya",
		र: "ra",
		ल: "la",
		ଳ: "Ḷa",
		व: "va",
		श: "śa",
		ष: "Ṣa",
		स: "sa",
		ह: "ha",
	},
	vowels: {
		अ: "a",
		आ: "aa",
		इ: "e",
		ई: "ee",
		उ: "o",
		ऊ: "oo",
		ऋ: "ru",
		ए: "ae",
		ऐ: "aei",
		ओ: "ou",
		औ: "oui",
	},
	punctuation: {
		"।": "।",
		"॥": "॥",
		"॰": "॰",
		ऽ: "ऽ",
		ॐ: "ॐ",
		"ः": "ः",
		"ँ": "ँ",
		"ं": "ं",
		"़": "़",
	},
	numbers: {
		0: "०",
		1: "१",
		2: "२",
		3: "३",
		4: "४",
		5: "५",
		6: "६",
		7: "७",
		8: "८",
		9: "९",
	},
};

// punctuation: {
//   comma: ",",
//   full_stop: ".",
//   question_mark: "?",
//   exclamation_mark: "!",
//   semicolon: ";",
//   colon: ":",
//   ellipsis: "…",
//   hyphen: "-",
//   en_dash: "–",
//   em_dash: "—",
//   single_quotation_mark: "'",
//   double_quotation_mark: '"',
//   parentheses: "()",
//   square_brackets: "[]",
//   curly_brackets: "{}",
//   angle_brackets: "<>",
//   slash: "/",
//   backslash: "\\",
//   ampersand: "&",
//   asterisk: "*",
//   hash: "#",
//   percent: "%",
//   caret: "^",
//   underscore: "_",
//   at_sign: "@",
//   dollar_sign: "$",
//   plus_sign: "+",
//   minus_sign: "-",
//   equals_sign: "=",
//   vertical_bar: "|",
//   tilde: "~",
//   grave_accent: "`",
// },
